---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ cont_name }}'
    consul_services:
      - name: '{{ cont_name }}'
        tags: ['logging']
        # we advertise the port with basic auth
        port: '{{ es_api_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        checks:
          - id: '{{ cont_name }}-health'
            name: ElasticHQ Healthcheck
            type: http
            http: 'http://localhost:{{ cont_port }}/api/clusters'
