---
- name: Create config dir
  file:
    path: '{{ es_hq_cont_vol }}/conf'
    state: directory

- name: Copy over logging config
  copy:
    src: logger.json
    dest: '{{ es_hq_cont_vol }}/conf/logger.json'

- name: 'Start container: {{ es_hq_cont_name }}'
  docker_container:
    name: '{{ es_hq_cont_name }}'
    image: '{{ es_hq_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: python
    command: |
      /src/application.py
      --port={{ es_hq_cont_port }}
      --host={{ es_hq_cont_addr }}
      {{ "--debug" if es_hq_cont_debug else "" }}
    links:
      - '{{ es_hq_lb_cont_name | mandatory }}:es'
    env:
      HQ_DEFAULT_URL: 'http://es:{{ es_hq_lb_port }}'
    ports:
      - '0.0.0.0:{{ es_hq_cont_port }}:{{ es_hq_cont_port }}'
    volumes:
      - '{{ es_hq_cont_vol }}/conf/logger.json:/src/elastichq/config/logger.json'
