---
- name: Start oauth2-proxy container
  docker_container:
    name: '{{ cont_name }}-oauth'
    image: '{{ oauth2_proxy_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: /bin/oauth2_proxy
    links:
      - '{{ cont_name }}:upstream'
    ports:
      - '127.0.0.1:8090:8090'
    command: |
      --email-domain='*'
      --provider='github'
      --github-org='status-im'
      --cookie-domain='{{ es_hq_domain | mandatory }}'
      --cookie-secret='{{ es_hq_cookie_secret || mandatory }}'
      --client-id='{{ es_hq_oauth_client_id || mandatory }}'
      --client-secret='{{ es_hq_oauth_client_secret || mandatory }}'
      --redirect-url='https://{{ es_hq_domain | mandatory }}/oauth2/callback'
      --http-address='0.0.0.0:{{ es_hq_oauth_port }}'
      --upstream='http://upstream:{{ es_cont_port }}/'
      --request-logging=false
