---
- name: Install full nginx for limit_req module
  apt:
    name: nginx-full

- name: 'Configure nginx proxy for: {{ es_hq_domain }}'
  include_role:
    name: nginx
  vars:
    nginx_sites:
      elasticsearch_hq:
        - listen 80
        - listen 443 ssl

        - server_name {{ es_hq_domain }}

        - ssl_certificate     /certs/origin.crt
        - ssl_certificate_key /certs/origin.key

        - location / {
            proxy_set_header Host $host;
            proxy_pass http://127.0.0.1:{{ es_hq_oauth_port }}/;
          }
